---
name: PyBullet

on:
  push:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  workflow_dispatch:

env:
  PYBULLET_REPO: https://github.com/physics-playground/Bullet
  PYBULLET_REF: 3.22

jobs:
  python_sdist:
    name: pybullet sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PyBullet
        uses: actions/checkout@v2

      - name: Install a python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build sdist
        run: |
          python -V
          python -m pip install build
          python -m build .

          # Ensure exactly one artifact was produced.
          [[ $(shopt -s nullglob; ls dist/*.tar.gz | wc -w) == 1 ]] || {
            echo "Unexpected content in dist dir: '$(ls dist/*.tar.gz)'."
            exit 1
          }

      - name: Test sdist
        run: |
          # Pass no extra args.
          # We should auto-install with pybullet since it's present.
          python -m pip install dist/*.tar.gz -v

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.tar.gz
